version: '3.8'
services:
  springboot:
    build:
      context: ./springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    ulimits:
      nofile:
        soft: 4096  # Soft limit for open files
        hard: 4096  # Hard limit for open files
      nproc: 4096   # Limit for the number of processes

  nginx:
    image: nginx:1.18.0
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-logs:/var/log/nginx # Mount the NGINX log directory to the host
    ports:
      - "8666:8666"
      - "8181:8181"
    depends_on:
      - springboot
    networks:
      - app-network
    ulimits:
      nofile:
        soft: 4096  # Soft limit for open files
        hard: 4096  # Hard limit for open files
      nproc: 4096   # Limit for the number of processes

networks:
  app-network:
    driver: bridge