version: '3.8'

services:
  springboot:
    build:
      context: ./springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:1.18.0
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - springboot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
